### ISSUE TITLE
Unable to use ManagedBass.Fx from NuGet.

### ISSUE THREAD

**Issue by daCyuubi** [ManagedBass/ManagedBass#71] opened 2020-04-11 20:11 UTC
I keep getting `'Could not load file or assembly 'ManagedBass, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'`,  any ideas?

**Comment by olitee** [comment] 2020-05-02 11:26
I'm having the same issue with the latest 3.0.0 release. Are you using ManagedBass in a .NET Standard class library, or dotnet core application?

I think the problem is that a version number has been added to the ManagedBass .NET Standard DLL:

https://github.com/ManagedBass/ManagedBass/blob/f8b1337afad9cfbc0a4f2bd18c30970815a14568/src/Bass/Portable/Bass.csproj#L7

So the addon assemblies (BassFX, etc) are looking for version 3.0.0, but the actual ManagedBass.dll assembly version of the latest published version if v1.0.0 (remember, the nuget package version is separate from the version numbers of the assemblies it contains)

@MathewSachin any ideas?

**Comment by Cyuubi** [comment] 2020-05-02 22:19
.NET Core application

**Comment by Founntain** [comment] 2020-10-30 15:21
Same problem on .NET Core 3.1
Is there any solution yet?

**Comment by parksquare** [comment] 2021-06-15 18:28
This is the same problem with the latest Nuget packages for ManagedBass.Mix. Looks like the issue has already been corrected in source, the Nuget packages just need rebuilding and republishing to Nuget.org.

**Comment by parksquare** [comment] 2021-06-21 15:45
This was a blocker for me so have forked it, fixed it, and published interim pre-release Nuget packages as BassSharp. This will be fully maintained and any useful fixes upstream in ManagedBass will be merged in regularly.

**Comment by olitee** [comment] 2021-08-12 21:45
Thanks @parksquare - We're just about to release a new version of the packages which will fix these issues. 

We've automated the releases so hopefully updates can be be generated with ease - and not every 18 months! Stay tuned.

**Closed by olitee** 2021-08-12 21:45 UTC
